### ISSUE TITLE
Horizontal scroll bars

### ISSUE THREAD

**Issue by matthewjay15** [UCL-ECHILD/code.echild.ac.uk-website#41]
It would be better if all the scrollables had horizontal bars visibile. I'm not yet sure why they're not showing up.

**Comment by tony-stone** [comment]
I think the issue is that quarto is already rendering the tables to handle the horizontal overflow. This is done _**within**_ your (vertical overflow) scrollable div. We can probably apply appropriate styling to the quarto table (wrapped in a div [with a named class] to indicate the tables to which this should be applied).

**Comment by matthewjay15** [comment]
Do you mean when running the kable() function (or somethen else that might need to replace this)? I tried different settings in the css file but nothing seemed to work.

**Comment by tony-stone** [comment]
I think it'll just require adding some (one?) style definitions to the css file. I'll have a look next week.

**Comment by matthewjay15** [comment]
Thanks for looking at this, @tony-stone. We've now lost the vertical ones. The _quarto_master.yml in the page_tamplate folder file needs updating as the R script takes a copy of this and then adds to it when writing the new qmd files

**Comment by tony-stone** [comment]
> We've now lost the vertical ones.
Yes, was trying to solve this. 
> The _quarto_master.yml in the page_tamplate folder needs updating as the R script takes a copy of this and then adds to it when writing the new qmd files
Ah! This is the problem. You don't need to copy this into the files.

**Comment by tony-stone** [comment]
Reopened by revert #54

**Comment by tony-stone** [comment]
Reopened by #56

**Comment by tony-stone** [comment]
Reopened by #69

**Comment by tony-stone** [comment]
Mistakenly reopened. Closing.
